# Generated by Django 4.1.1 on 2022-09-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[(1, '3"'), (2, '4"'), (3, '5"'), (4, '6"'), (5, '7"'), (6, '8"'), (7, '9"'), (5, '10"'), (6, '11"')], max_length=4, verbose_name='MotorTipi')),
                ('serial_number', models.CharField(max_length=50, verbose_name='SeriNumarası')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_mark', models.CharField(max_length=50, verbose_name='Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_power', models.FloatField(verbose_name='MotorGücü')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_type', models.CharField(max_length=25, verbose_name='Tipi')),
                ('pump_breed', models.CharField(choices=[(1, 'KROM'), (2, 'NORİL'), (3, 'DÖKÜM')], max_length=5, verbose_name='Cinsi')),
                ('number_stages', models.PositiveIntegerField(default=0, verbose_name='KademeSayısı')),
                ('serial_number', models.CharField(max_length=50, verbose_name='SeriNumarası')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
                ('pump_mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.mark')),
            ],
        ),
        migrations.CreateModel(
            name='İnvertory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.PositiveIntegerField(unique=True, verbose_name='KuyuNumarası')),
                ('contry', models.CharField(choices=[('akçakale', 'AKÇAKALE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR'), ('merkez', 'MERKEZ')], max_length=11, verbose_name='iLÇE')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('disassembly_depth', models.PositiveIntegerField(verbose_name='DemontajDerinliği')),
                ('mounting_depth', models.PositiveIntegerField(verbose_name='MontajDerinliği')),
                ('tank_info', models.CharField(choices=[(1, 'TANK'), (2, 'ŞEBEKE'), (3, 'HAVUZ'), (4, 'DEPO'), (5, 'BOŞTA'), (6, 'AYAKLI DEPO')], max_length=11, verbose_name='DepoBilgisi')),
                ('pipe_type', models.CharField(max_length=50, verbose_name='Borutipi')),
                ('cable', models.CharField(max_length=15, verbose_name='Kablo')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.FloatField(blank=True, verbose_name='Debi')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.engine', verbose_name='Motor')),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.pump', verbose_name='Pompa')),
            ],
        ),
        migrations.AddField(
            model_name='engine',
            name='engine_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.mark', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='engine',
            name='engine_power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.power', verbose_name='MotorGücü'),
        ),
    ]
