# Generated by Django 4.1.1 on 2022-09-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_engine_number_remove_engine_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wellİnformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.PositiveIntegerField(unique=True, verbose_name='KuyuNumarası')),
                ('contry', models.CharField(choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR'), ('merkez', 'MERKEZ')], max_length=11, verbose_name='iLÇE')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
            ],
        ),
        migrations.RemoveField(
            model_name='i̇nvertory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='i̇nvertory',
            name='contry',
        ),
        migrations.RemoveField(
            model_name='i̇nvertory',
            name='well_number',
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.mark', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.power', verbose_name='MotorGücü'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.engine', verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='flow',
            field=models.FloatField(blank=True, default=0, verbose_name='Debi'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pump', verbose_name='Pompa'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='engine_mark',
            field=models.CharField(max_length=50, unique=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='power',
            name='engine_power',
            field=models.FloatField(unique=True, verbose_name='MotorGücü'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.mark'),
        ),
        migrations.AddField(
            model_name='i̇nvertory',
            name='well_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.welli̇nformation', verbose_name='Kuyu_Bilgisi'),
        ),
    ]
