# Generated by Django 4.1.1 on 2022-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_welli̇nformation_remove_i̇nvertory_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welli̇nformation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(choices=[('1', '3"'), ('2', '4"'), ('3', '5"'), ('4', '6"'), ('5', '7"'), ('6', '8"'), ('7', '9"'), ('8', '10"'), ('9', '11"')], max_length=4, verbose_name='MotorTipi'),
        ),
    ]
