# Generated by Django 4.1.1 on 2022-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_i̇nvertory_flow_alter_welli̇nformation_contry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nvertory',
            name='flow',
            field=models.CharField(blank=True, max_length=50, verbose_name='Debi'),
        ),
    ]
