# Generated by Django 4.1.1 on 2022-09-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_i̇nvertory_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welli̇nformation',
            options={'ordering': ('well_number',)},
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.power', verbose_name='Motor Gücü'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='engine_type',
            field=models.CharField(choices=[('1', '3"'), ('2', '4"'), ('3', '5"'), ('4', '6"'), ('5', '7"'), ('6', '8"'), ('7', '9"'), ('8', '10"'), ('9', '11"')], max_length=4, verbose_name='Motor Tipi'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='disassembly_depth',
            field=models.PositiveIntegerField(verbose_name='Demontaj Derinliği'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='mounting_depth',
            field=models.PositiveIntegerField(verbose_name='Montaj Derinliği'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='pipe_type',
            field=models.CharField(max_length=50, verbose_name='Boru Tipi'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='tank_info',
            field=models.CharField(choices=[('1', 'TANK'), ('2', 'ŞEBEKE'), ('3', 'HAVUZ'), ('4', 'DEPO'), ('5', 'BOŞTA'), ('6', 'AYAKLI DEPO')], max_length=11, verbose_name='Depo Bilgisi'),
        ),
        migrations.AlterField(
            model_name='i̇nvertory',
            name='well_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.welli̇nformation', verbose_name='Kuyu Bilgisi'),
        ),
        migrations.AlterField(
            model_name='power',
            name='engine_power',
            field=models.FloatField(unique=True, verbose_name='Motor Gücü'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='number_stages',
            field=models.PositiveIntegerField(default=0, verbose_name='Kademe Sayısı'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='pump_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.mark', verbose_name='Pompa Markası'),
        ),
        migrations.AlterField(
            model_name='welli̇nformation',
            name='well_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Kuyu Numarası'),
        ),
    ]
