# Generated by Django 4.1.1 on 2022-09-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_welli̇nformation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={'ordering': ('engine_power__engine_power',)},
        ),
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ('pump_type',)},
        ),
        migrations.CreateModel(
            name='ZeroEngineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Motor Seri Numarası')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.engine', verbose_name='Motor')),
            ],
        ),
    ]
