# Generated by Django 4.1.1 on 2022-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_engine_options_alter_pump_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇nvertory',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='welli̇nformation',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zeroenginestock',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Stok'),
        ),
    ]
