# Generated by Django 4.1.1 on 2022-09-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_i̇nvertory_update_at_welli̇nformation_update_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroOtherStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('subcategory', models.CharField(max_length=50, verbose_name='Kategori')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='Stok')),
            ],
        ),
        migrations.CreateModel(
            name='ZeroPumpStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Pompa Seri Numarası')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='Stok')),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pump', verbose_name='Pompa')),
            ],
        ),
    ]
