# Generated by Django 4.1.1 on 2022-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_zerootherstock_zeropumpstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zeropumpstock',
            old_name='engine_serial_number',
            new_name='pump_serial_number',
        ),
        migrations.AlterField(
            model_name='zerootherstock',
            name='subcategory',
            field=models.CharField(max_length=50, verbose_name='Alt Kategori'),
        ),
    ]
