# Generated by Django 4.1.1 on 2022-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_engine_serial_number_zeropumpstock_pump_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welli̇nformation',
            name='well_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kuyu Numarası'),
        ),
    ]
