# Generated by Django 4.0.4 on 2022-10-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_welli̇nformation_well_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwondPumpStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Pompa Seri Numarası')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='Stok')),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.engine', verbose_name='Pompa')),
            ],
        ),
        migrations.CreateModel(
            name='TwondEngineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Motor Seri Numarası')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miktar')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='Stok')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.engine', verbose_name='Motor')),
            ],
        ),
    ]
