# Generated by Django 4.0.4 on 2022-10-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_twondpumpstock_twondenginestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twondpumpstock',
            name='pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pump', verbose_name='Pompa'),
        ),
    ]
