# Generated by Django 4.1.1 on 2022-10-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_twondpumpstock_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twondenginestock',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='twondpumpstock',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miktar'),
        ),
        migrations.CreateModel(
            name='RepairStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_serial_number', models.CharField(blank=True, max_length=50, verbose_name='Motor Seri Numarası')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miktar')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='Stok')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.engine', verbose_name='Motor')),
            ],
        ),
    ]
