# Generated by Django 4.1.1 on 2022-10-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_twondenginestock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇nvertory',
            options={'ordering': ('well_number',)},
        ),
        migrations.RemoveField(
            model_name='i̇nvertory',
            name='well_information',
        ),
        migrations.AddField(
            model_name='i̇nvertory',
            name='contry',
            field=models.CharField(blank=True, choices=[('akçakale', 'AKÇAKALE'), ('eyyübiye', 'EYYÜBİYE'), ('birecik', 'BİRECİK'), ('bozova', 'BOZOVA'), ('ceylanpınar', 'CEYLANPINAR'), ('halfeti', 'HALFETİ'), ('haliliye', 'HALİLİYE'), ('harran', 'HARRAN'), ('hilvan', 'HİLVAN'), ('karaköprü', 'KARAKÖPRÜ'), ('siverek', 'SİVEREK'), ('suruç', 'SURUÇ'), ('viranşehir', 'VİRANŞEHİR')], max_length=11, verbose_name='iLÇE'),
        ),
        migrations.AddField(
            model_name='i̇nvertory',
            name='well_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Kuyu Numarası'),
        ),
    ]
