# Generated by Django 4.1.1 on 2022-10-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_work_orders_well_information'),
        ('inventory', '0016_alter_i̇nvertory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wellİnformation',
        ),
    ]
