# Generated by Django 4.1.1 on 2022-10-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_i̇nvertory_contry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nvertory',
            name='well_number',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Kuyu Numarası'),
        ),
    ]
