# Generated by Django 4.1.1 on 2022-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_i̇nvertory_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇nvertory',
            name='adress',
            field=models.CharField(max_length=50, verbose_name='Adres'),
        ),
    ]
