# Generated by Django 4.1.1 on 2022-09-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_rename_engine_serial_number_zeropumpstock_pump_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_orders_number', models.PositiveIntegerField(unique=True, verbose_name='Numara')),
                ('status', models.CharField(choices=[('1', 'DEMONTAJ BEKLİYOR'), ('2', 'TAMİR EDİLİYOR'), ('3', 'MONTAJ BEKLİYOR'), ('4', 'KAPANDI')], max_length=17, verbose_name='Durum')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('well_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.welli̇nformation', verbose_name='Kuyu Bilgisi')),
            ],
        ),
        migrations.CreateModel(
            name='DisAssembly_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disassembly_orders_number', models.PositiveIntegerField(null=True, unique=True, verbose_name='Demontaj numarası')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('invertory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.i̇nvertory', verbose_name='Envarter')),
                ('work_orders_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.work_orders', verbose_name='İş Emri')),
            ],
        ),
        migrations.CreateModel(
            name='Assembly_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_orders_number', models.PositiveIntegerField(null=True, unique=True, verbose_name='Montaj numarası')),
                ('comment', models.TextField(blank=True, verbose_name='Açıklama')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('invertory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.i̇nvertory', verbose_name='Envarter')),
                ('work_orders_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.work_orders', verbose_name='İş Emri')),
            ],
        ),
    ]
