# Generated by Django 4.1.1 on 2022-10-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly_orders',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='disassembly_orders',
            name='comment',
        ),
    ]
