# Generated by Django 4.1.1 on 2022-10-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_repair_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_orders',
            name='job_done',
            field=models.CharField(blank=True, choices=[('1', 'DEMONTAJ BEKLİYOR'), ('2', 'ATÖLYEDE TAMİR BEKLİYOR'), ('3', 'TAMİR EDİLİYOR'), ('4', 'ATÖLYEDE MONTAJ BEKLİYOR'), ('5', 'MONTAJ BEKLİYOR'), ('6', 'KAPANDI')], max_length=17, null=True, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='repair_orders',
            name='repair_orders_number',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Tamir numarası'),
        ),
        migrations.AlterField(
            model_name='work_orders',
            name='status',
            field=models.CharField(choices=[('1', 'DEMONTAJ BEKLİYOR'), ('2', 'ATÖLYEDE TAMİR BEKLİYOR'), ('3', 'TAMİR EDİLİYOR'), ('4', 'ATÖLYEDE MONTAJ BEKLİYOR'), ('5', 'MONTAJ BEKLİYOR'), ('6', 'KAPANDI')], max_length=17, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='workshop_orders',
            name='workshop_orders_number',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Tamir numarası'),
        ),
    ]
