# Generated by Django 4.1.1 on 2022-10-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_i̇nvertory_options_and_more'),
        ('orders', '0006_alter_work_orders_job_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_orders',
            name='well_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.i̇nvertory', verbose_name='Kuyu Bilgisi'),
        ),
    ]
