# Generated by Django 4.1.1 on 2022-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_work_orders_well_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_orders',
            old_name='well_information',
            new_name='invertory',
        ),
        migrations.RemoveField(
            model_name='assembly_orders',
            name='invertory',
        ),
        migrations.RemoveField(
            model_name='disassembly_orders',
            name='invertory',
        ),
        migrations.RemoveField(
            model_name='repair_orders',
            name='invertory',
        ),
        migrations.RemoveField(
            model_name='workshop_orders',
            name='invertory',
        ),
        migrations.AddField(
            model_name='assembly_orders',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='disassembly_orders',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
    ]
