# Generated by Django 4.1.1 on 2022-10-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_well_information_work_orders_invertory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly_orders',
            name='status',
            field=models.CharField(choices=[('passive', 'PASİF'), ('active', 'AKTİF')], default='active', max_length=7),
        ),
        migrations.AddField(
            model_name='disassembly_orders',
            name='status',
            field=models.CharField(choices=[('passive', 'PASİF'), ('active', 'AKTİF')], default='active', max_length=7),
        ),
        migrations.AddField(
            model_name='repair_orders',
            name='status',
            field=models.CharField(choices=[('passive', 'PASİF'), ('active', 'AKTİF')], default='active', max_length=7),
        ),
        migrations.AddField(
            model_name='workshop_orders',
            name='status',
            field=models.CharField(choices=[('passive', 'PASİF'), ('active', 'AKTİF')], default='active', max_length=7),
        ),
    ]
