# Generated by Django 4.1.1 on 2022-10-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_repair_orders_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disassembly_orders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='repair_orders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workshop_orders',
            name='status',
        ),
    ]
