# Generated by Django 4.1.1 on 2022-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_disassembly_orders_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disassembly_orders',
            old_name='disassembly_orders_number',
            new_name='orders_number',
        ),
        migrations.AddField(
            model_name='disassembly_orders',
            name='status',
            field=models.CharField(choices=[('passive', 'PASİF'), ('active', 'AKTİF')], default='active', max_length=7),
        ),
    ]
