# Generated by Django 4.1.1 on 2022-11-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_disassembly_orders_number_disassembly_orders_orders_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop_orders',
            old_name='workshop_orders_number',
            new_name='orders_number',
        ),
        migrations.AddField(
            model_name='workshop_orders',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
    ]
