# Generated by Django 4.1.1 on 2022-11-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_orders_number_repair_orders_repair_orders_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly_orders',
            old_name='assembly_orders_number',
            new_name='orders_number',
        ),
    ]
